# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metricReport.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='metricReport.proto',
  package='com.ioe',
  syntax='proto3',
  serialized_pb=_b('\n\x12metricReport.proto\x12\x07\x63om.ioe\"\xf4\x01\n\x13MetricReportRequest\x12;\n\nmetricData\x18\x01 \x03(\x0b\x32\'.com.ioe.MetricReportRequest.MetricData\x1a\x9f\x01\n\nMetricData\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12>\n\x06metric\x18\x02 \x03(\x0b\x32..com.ioe.MetricReportRequest.MetricData.Metric\x1a>\n\x06Metric\x12\x0f\n\x07pointId\x18\x01 \x01(\x03\x12\r\n\x05value\x18\x02 \x01(\x01\x12\x14\n\x0chasException\x18\x03 \x01(\x08\x42\x10\x42\x0cMetricReportH\x03\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_METRICREPORTREQUEST_METRICDATA_METRIC = _descriptor.Descriptor(
  name='Metric',
  full_name='com.ioe.MetricReportRequest.MetricData.Metric',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pointId', full_name='com.ioe.MetricReportRequest.MetricData.Metric.pointId', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='com.ioe.MetricReportRequest.MetricData.Metric.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hasException', full_name='com.ioe.MetricReportRequest.MetricData.Metric.hasException', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=214,
  serialized_end=276,
)

_METRICREPORTREQUEST_METRICDATA = _descriptor.Descriptor(
  name='MetricData',
  full_name='com.ioe.MetricReportRequest.MetricData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='com.ioe.MetricReportRequest.MetricData.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='metric', full_name='com.ioe.MetricReportRequest.MetricData.metric', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_METRICREPORTREQUEST_METRICDATA_METRIC, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=276,
)

_METRICREPORTREQUEST = _descriptor.Descriptor(
  name='MetricReportRequest',
  full_name='com.ioe.MetricReportRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='metricData', full_name='com.ioe.MetricReportRequest.metricData', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_METRICREPORTREQUEST_METRICDATA, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=276,
)

_METRICREPORTREQUEST_METRICDATA_METRIC.containing_type = _METRICREPORTREQUEST_METRICDATA
_METRICREPORTREQUEST_METRICDATA.fields_by_name['metric'].message_type = _METRICREPORTREQUEST_METRICDATA_METRIC
_METRICREPORTREQUEST_METRICDATA.containing_type = _METRICREPORTREQUEST
_METRICREPORTREQUEST.fields_by_name['metricData'].message_type = _METRICREPORTREQUEST_METRICDATA
DESCRIPTOR.message_types_by_name['MetricReportRequest'] = _METRICREPORTREQUEST

MetricReportRequest = _reflection.GeneratedProtocolMessageType('MetricReportRequest', (_message.Message,), dict(

  MetricData = _reflection.GeneratedProtocolMessageType('MetricData', (_message.Message,), dict(

    Metric = _reflection.GeneratedProtocolMessageType('Metric', (_message.Message,), dict(
      DESCRIPTOR = _METRICREPORTREQUEST_METRICDATA_METRIC,
      __module__ = 'metricReport_pb2'
      # @@protoc_insertion_point(class_scope:com.ioe.MetricReportRequest.MetricData.Metric)
      ))
    ,
    DESCRIPTOR = _METRICREPORTREQUEST_METRICDATA,
    __module__ = 'metricReport_pb2'
    # @@protoc_insertion_point(class_scope:com.ioe.MetricReportRequest.MetricData)
    ))
  ,
  DESCRIPTOR = _METRICREPORTREQUEST,
  __module__ = 'metricReport_pb2'
  # @@protoc_insertion_point(class_scope:com.ioe.MetricReportRequest)
  ))
_sym_db.RegisterMessage(MetricReportRequest)
_sym_db.RegisterMessage(MetricReportRequest.MetricData)
_sym_db.RegisterMessage(MetricReportRequest.MetricData.Metric)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('B\014MetricReportH\003'))
# @@protoc_insertion_point(module_scope)
